### ISSUE TITLE
Problem with 404 on files (with file extension)

### ISSUE THREAD

**Issue by ATO-Matze** [unic/SitecoreErrorManager#10]
Hello,

we configure the 404 that it points to the sitecore item /error/404.

If we now enter an url like http://domain.com/file.txt (not existing) the redirect points to 
http://domain.com/error/404?404;http://domain.com/file.txt

But then the 404 page is just an empty white page.

Do you have any hint what the problem might be or what configuration we have to set?

Thanks in advance!

Best regards,
Matthias

**Comment by retohugi** [comment]
Hi Matthias,

The redirected Url you mention does not look familiar to me in the module context. 
Can you reproduce the isdue on your local dev instance? 
Can you confirm that direct http requests to the configured 404 pages work?
Can you check the patch order in the httpRequestBegin pipeline is ok? (Copy&paste the output of showconfig.aspx here if in doubt)

Cheers, reto

**Comment by ATO-Matze** [comment]
Hi Reto,

thanks for reply.


We found out that it is a problem with another Marketplace-Module called ParTech.Modules.SeoUrl.

If we disable this module, your ErrorManager works fine for urls like www.domain.com/foo<http://www.domain.com/foo> but for urls like www.domain.com/foo.txt<http://www.domain.com/foo.txt> the IIS shows the standard error page and not the custom one from sitecore.

Do you have any hint how to configure the IIS that it delivers the sitecore page with status code 404?

Thanks in advance!

Best regards,
Matthias


----------------------------------------

Von: Reto Hugi [mailto:notifications@github.com]
Gesendet: Dienstag, 31. Mai 2016 17:13
An: unic/SitecoreErrorManager <SitecoreErrorManager@noreply.github.com>
Cc: ATO interactive | Matthias Holze <matthias.holze@ato.de>; Author <author@noreply.github.com>
Betreff: Re: [unic/SitecoreErrorManager] Problem with 404 on files (with file extension) (#10)


Hi Matthias,

The redirected Url you mention does not look familiar to me in the module context.
Can you reproduce the isdue on your local dev instance?
Can you confirm that direct http requests to the configured 404 pages work?
Can you check the patch order in the httpRequestBegin pipeline is ok? (Copy&paste the output of showconfig.aspx here if in doubt)

Cheers, reto

**Comment by retohugi** [comment]
Hi Matthias

Have you tried setting `httpErrors` to `errorMode="Custom"` in the Web.config section `system.webServer`? You can find an example in our [documentation](https://github.com/unic/SitecoreErrorManager/wiki/Configuration#configure-other-sub-status-codes).

Let me know if this helps.

Cheers, reto

**Comment by retohugi** [comment]
Hi Matthias

I hope you've been able to fix your issue with the ErrorManager. Let me know if you still have troubles. Otherwise I'm going to resolve this issue in the next couple of days.

Cheers,
Reto
