### ISSUE TITLE
Modify 404 behaviour for CMS Managed Media Items

### ISSUE THREAD

**Issue by kreiswelt** [unic/SitecoreErrorManager#12]
Hi,

Is there an option to have any CMS managed media items that are not found to return minimal body content or static file? Currently it shows friendly 404 error page which can be expensive request 

On top of that, all the browser will only display a big RED X for wrong images

Thanks

**Comment by retohugi** [comment]
Hi, thanks for your contribution. You're making a valid point and we'll review your PR asap.

BR, reto

**Comment by studert** [comment]
Thx for the pull request. It has been merged and will be include in the next release (planned within the next few days).
